import os

# Tasks
VEXTENSION = "mp4"
AEXTENSION = "mp3"
DOWNLOAD_THREADS = 1
DOWNLOAD_PATH = "/tmp/"
DEBUG = False
DEFAULT_TIMEOUT = 10
TOO_MANY_REQUESTS_TIMEOUT = 30
BLOCKED_WORKER_FILE = "blocked_workers.csv"
MINIMUM_BLOCKED_TIME = 60 * 45
AQUALITY = "64k"
YT_FORMAT = f"b[ext={VEXTENSION}]"
YT_FALLBACK_FORMAT = None
KEYFRAMES_ONLY = True

MANAGEMENT_PROCESS_SHARD_TIMEOUT = 60 * 60 * 1  # 1h


# Setup
SCRIPT_PATH = os.environ.get("CELERY_SETUP_SCRIPT", "setup_celery.sh")
DEFAULT_USER = os.environ.get("CELERY_USER", "celery")
DEFAULT_CELERY_PATH = os.environ.get("CELERY_PATH", "celery")
DEFAULT_MODULE = os.environ.get("CELERY_MODULE", "celery_config")
DEFAULT_CELERY_ENV_SETUP = os.environ.get("CELERY_ENV_SETUP", "")
DEFAULT_CELERY_PROCESS_PATTERN = os.environ.get(
    "CELERY_PROCESS_PATTERN",
    f"{DEFAULT_CELERY_PATH} -A {DEFAULT_MODULE} worker",
)
REQUIRED_MOUNT_PATH = os.environ.get("DOWNLOAD_REQUIRED_MOUNT", "")

__all__ = [
    "VEXTENSION",
    "AEXTENSION",
    "DOWNLOAD_THREADS",
    "DOWNLOAD_PATH",
    "DEBUG",
    "DEFAULT_TIMEOUT",
    "TOO_MANY_REQUESTS_TIMEOUT",
    "BLOCKED_WORKER_FILE",
    "MINIMUM_BLOCKED_TIME",
    "AQUALITY",
    "YT_FORMAT",
    "YT_FALLBACK_FORMAT",
    "KEYFRAMES_ONLY",
    "SCRIPT_PATH",
    "DEFAULT_USER",
    "DEFAULT_CELERY_PATH",
    "DEFAULT_MODULE",
    "DEFAULT_CELERY_ENV_SETUP",
    "DEFAULT_CELERY_PROCESS_PATTERN",
    "REQUIRED_MOUNT_PATH",
]
